"""
Shared forge feedback utilities for Claude agents.

Provides functions to extract structured comments, line comments, and vote
scores from agent-generated markdown reports, ready for posting back to
Gerrit, GitHub, or GitLab via the ForgeClient.

Originally from code-review-agent; moved here so the DevStack Test Agent
and CI Failure Agent can use the same utilities without duplication.
"""
import re

from .utils import sanitize_for_forge
from .forge_client import LineComment


# ── helpers ──────────────────────────────────────────────────────────────────

def _section(content: str, *headers: str) -> str:
    """Extract the text of the first matching section up to the next heading."""
    for header in headers:
        _hm = re.match(r'^(#+)', header)
        level = len(_hm.group(1)) if _hm else 2
        pattern = re.escape(header) + r'(.*?)(?=\n#{1,' + str(level) + r'} |\Z)'
        m = re.search(pattern, content, re.DOTALL | re.IGNORECASE)
        if m:
            return m.group(1).strip()
    return ""


def _first_n_chars(text: str, n: int) -> str:
    """Return at most n chars, cutting at a paragraph boundary if possible."""
    if len(text) <= n:
        return text
    cut = text.rfind("\n\n", 0, n)
    return text[:cut] if cut > n // 2 else text[:n]


def _has_blocking_issues(review_content: str) -> bool:
    """Return True if the review contains critical or major issues."""
    blocking_patterns = [
        r'🔴',
        r'\bmust\s+fix\b',
        r'\bcritical\b(?!\s+path)',
        r'\bsecurity\s+(?:issue|vulnerability|bug|risk)\b',
        r'\bbreaking\s+change\b',
    ]
    for pat in blocking_patterns:
        if re.search(pat, review_content, re.IGNORECASE):
            return True
    return False


def _extract_comment_text(raw: str) -> str:
    """Pull the human-readable comment from a line-reference body block."""
    m = re.search(r'\*\*Comment\*\*:\s*(.+?)(?=\n-\s+\*\*|\Z)', raw, re.DOTALL)
    if m:
        return sanitize_for_forge(m.group(1).strip())
    for line in raw.splitlines():
        line = line.strip().lstrip('- ')
        if line and not line.startswith('**Severity') and not line.startswith('**Suggestion'):
            return sanitize_for_forge(line)
    return ""


# ── public API ────────────────────────────────────────────────────────────────

def extract_forge_comment(review_content: str, model_name: str) -> str:
    """Build a forge comment from a code review markdown report.

    Extracts the review summary, test results, key findings, and verdict.
    Caps at 7500 chars. Returns a formatted comment with AI attribution.

    Args:
        review_content: Full text of the generated review markdown.
        model_name:     Model identifier for the attribution line.

    Returns:
        Formatted comment string including AI attribution header/footer.
    """
    MAX_CHARS = 7500

    clean = re.split(r'\n---\n\n## Token Usage', review_content, maxsplit=1)[0].strip()
    clean = re.split(r'\n## DevStack Integration Testing\b', clean, maxsplit=1)[0].strip()
    clean = re.split(r'\n## Test Environment\b', clean, maxsplit=1)[0].strip()
    clean = re.split(r'\n## Tests Executed\b', clean, maxsplit=1)[0].strip()

    body = _first_n_chars(clean, MAX_CHARS)
    body = sanitize_for_forge(body)

    attribution_header = f"*Reviewed by {model_name}*\n\n"
    attribution_footer = "\n\n---\n*This review was generated by an AI and may contain errors.*"
    return attribution_header + body + attribution_footer


def extract_line_comments(review_content: str) -> list:
    """Parse inline line comments from a code review markdown report.

    Looks for the structured format produced by the code review prompt:

        ### File: `octavia/path/to/file.py`
        **Line 45-52**:
        - **Comment**: explanation

    Returns a list of LineComment objects; empty list if none are found.
    """
    comments: list[LineComment] = []

    section_m = re.search(
        r'## Detailed Review Comments\s*(.*?)(?=\n## |\Z)',
        review_content,
        re.DOTALL | re.IGNORECASE,
    )
    if not section_m:
        return comments

    section = section_m.group(1)
    file_blocks = re.split(r'\n### File:\s*`?([^`\n]+)`?\s*\n', "\n" + section)

    i = 1
    while i + 1 < len(file_blocks):
        file_path = file_blocks[i].strip()
        block_content = file_blocks[i + 1]
        i += 2

        line_refs = re.split(r'\*\*Lines?\s+(\d+)(?:[-–](\d+))?\*\*\s*', block_content)

        j = 1
        while j + 2 < len(line_refs):
            line_start = int(line_refs[j])
            line_end_raw = line_refs[j + 1]
            line_end = int(line_end_raw) if line_end_raw else None
            body = line_refs[j + 2]

            comment_text = _extract_comment_text(body)
            if comment_text:
                comments.append(LineComment(
                    file_path=file_path,
                    line=line_start,
                    message=comment_text,
                    line_end=line_end,
                ))
            j += 3

    return comments


def determine_vote(review_content: str, config: dict) -> "int | None":
    """Map a review verdict to a forge vote score.

    Returns:
        +1 (approval_score), 0 (minor_score), -1 (major_score), or None
        if voting is disabled in config.
    """
    if not config.get("feedback_voting", True):
        return None

    approval_score = config.get("feedback_approval_score", 1)
    major_score = config.get("feedback_major_score", -1)
    minor_score = config.get("feedback_minor_score", 0)

    text = review_content.lower()

    approve_patterns = [
        r'\brecommendation[:\s*]*.*\bapprove\b',
        r'\bverdict[:\s*]*.*\bapprove\b',
        r'✅.*\bapprove\b',
        r'\bapprove\b.*(?:ready|merge|lgtm)',
        r'✅\s*approve',
    ]
    for pat in approve_patterns:
        if re.search(pat, text) and not _has_blocking_issues(review_content):
            return approval_score

    request_change_patterns = [
        r'\brequest\s+changes?\b',
        r'🔄.*request',
        r'\bverdict[:\s*]*.*\bchanges?\b',
    ]
    for pat in request_change_patterns:
        if re.search(pat, text):
            return major_score if _has_blocking_issues(review_content) else minor_score

    if _has_blocking_issues(review_content):
        return major_score

    if re.search(r'🟡|minor|suggestion|nit\b', text):
        return minor_score

    return None


def extract_ci_forge_comment(report_content: str, model_name: str) -> str:
    """Build a forge comment from a CI failure analysis report.

    Extracts the overall recommendation and per-job summary table.
    Always informational (no vote).

    Args:
        report_content: Full text of the CI failure analysis markdown.
        model_name:     Model identifier for the attribution line.

    Returns:
        Formatted comment string including AI attribution.
    """
    MAX_CHARS = 6000

    clean = re.split(r'\n---\n\n## Token Usage', report_content, maxsplit=1)[0].strip()

    rec_section = _section(clean, "## Overall Recommendation", "## Recommendation")
    table_m = re.search(r'(\|[^\n]+\|\n\|[-:| ]+\|\n(?:\|[^\n]+\|\n)+)', clean)
    table = table_m.group(1).strip() if table_m else ""

    parts = []
    if rec_section:
        parts.append("## Overall Recommendation\n\n" + _first_n_chars(rec_section, 2000))
    if table:
        parts.append("## Failing Jobs\n\n" + table)
    if not parts:
        parts.append(_first_n_chars(clean, MAX_CHARS))

    body = _first_n_chars("\n\n".join(parts), MAX_CHARS)
    body = sanitize_for_forge(body)

    attribution_header = f"*CI analysis by {model_name}*\n\n"
    attribution_footer = "\n\n---\n*This analysis was generated by an AI and may contain errors.*"
    return attribution_header + body + attribution_footer


def extract_devstack_forge_comment(report_content: str, model_name: str) -> str:
    """Build a forge comment from a DevStack testing_report_*.md file.

    Extracts the Test Results Summary (overall status, pass/fail counts, key
    findings). Always informational — no vote, no line comments.

    Args:
        report_content: Full text of the DevStack testing report markdown.
        model_name:     Model identifier for the attribution line.

    Returns:
        Formatted comment string including AI attribution.
    """
    MAX_CHARS = 5000

    # Strip the original code-review content (before the DevStack section)
    devstack_section = ""
    ds_m = re.search(
        r'# DevStack Integration Testing\s*(.*)',
        report_content,
        re.DOTALL | re.IGNORECASE,
    )
    if ds_m:
        devstack_section = ds_m.group(1).strip()
    else:
        # Fall back to full content if no DevStack section found
        devstack_section = report_content

    # Strip token usage
    devstack_section = re.split(
        r'\n---\n\n## Token Usage', devstack_section, maxsplit=1
    )[0].strip()

    # Extract overall status line
    status_m = re.search(
        r'\*\*Overall Status\*\*[:\s]*(.*?)(?=\n|$)',
        devstack_section,
        re.IGNORECASE,
    )
    status_line = status_m.group(1).strip() if status_m else ""

    # Extract Test Results Summary section
    summary_section = _section(devstack_section, "## Test Results Summary")

    parts = []
    if status_line:
        parts.append(f"**Overall Status**: {status_line}")
    if summary_section:
        parts.append("## Test Results Summary\n\n" + _first_n_chars(summary_section, 2000))
    if not parts:
        parts.append(_first_n_chars(devstack_section, MAX_CHARS))

    body = _first_n_chars("\n\n".join(parts), MAX_CHARS)
    body = sanitize_for_forge(body)

    attribution_header = f"*DevStack integration tests by {model_name}*\n\n"
    attribution_footer = "\n\n---\n*This report was generated by an AI and may contain errors.*"
    return attribution_header + body + attribution_footer
