#!/usr/bin/env python3
"""
Analyze CI failures for a single Gerrit change using AI.

This script is the AI-powered core of the CI Failure Analysis Agent. It:
  1. Reads failure data (jobs, log URLs) from a JSON file
  2. Builds a structured analysis prompt
  3. Invokes an AI agent (via claude-agent-sdk) to fetch logs and analyze failures
  4. Saves a comprehensive markdown report

Usage (standalone):
    ./analyze_ci_failure.py --failure-data /tmp/failure_data.json
    ./analyze_ci_failure.py --failure-data /tmp/failure_data.json --print-prompt
    ./analyze_ci_failure.py --failure-data /tmp/failure_data.json --output-dir ~/my_reports

Usage (called by ci_failure_agent.py):
    python analyze_ci_failure.py --failure-data /tmp/ci_failure_abc123.json --output-dir ~/octavia_ci_failures

The failure-data JSON format:
{
    "change_number": "982567",
    "patchset": "3",
    "project": "openstack/octavia",
    "pipeline": "check",
    "gerrit_url": "https://review.opendev.org/c/openstack/octavia/+/982567",
    "sequence": 1,
    "jobs": [
        {
            "job_name": "octavia-v2-dsvm-scenario-centos-9-stream-ovn",
            "uuid": "abc123def456...",
            "log_url": "https://storage.bhs.logs.ovh.net/v1/.../",
            "duration": 2843.0,
            "voting": true,
            "end_time": "2026-04-30T10:47:23",
            "nodeset": "centos-9-stream"
        }
    ]
}

Tool-agnostic use:
    Run with --print-prompt to get the formatted prompt without invoking any AI.
    You can then paste the prompt into Claude.ai, Cursor, or any other AI tool.
"""
import asyncio
import json
import sys
import argparse
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from config import load_config
from prompts import get_ci_failure_prompt
from agents_lib import format_usage_info, create_forge_client, sanitize_for_forge
from agents_lib.utils import slugify

CONFIG = load_config()


def _build_forge_comment(report_content: str, model_name: str) -> str:
    """Extract a concise forge comment from a CI failure report."""
    import re

    MAX_CHARS = 6000

    # Strip token usage section
    clean = re.split(r'\n---\n\n## Token Usage', report_content, maxsplit=1)[0].strip()

    # Try to pull the Overall Recommendation section
    rec_m = re.search(
        r'## (?:Overall\s+)?Recommendation\s*(.*?)(?=\n## |\Z)',
        clean, re.DOTALL | re.IGNORECASE,
    )
    rec_section = rec_m.group(1).strip() if rec_m else ""

    # First markdown table (failing jobs summary)
    table_m = re.search(r'(\|[^\n]+\|\n\|[-:| ]+\|\n(?:\|[^\n]+\|\n)+)', clean)
    table = table_m.group(1).strip() if table_m else ""

    parts = []
    if rec_section:
        cut = rec_section[:2000]
        parts.append("## Overall Recommendation\n\n" + cut)
    if table:
        parts.append("## Failing Jobs\n\n" + table)
    if not parts:
        parts.append(clean[:MAX_CHARS])

    body = "\n\n".join(parts)
    if len(body) > MAX_CHARS:
        body = body[:MAX_CHARS]
    body = sanitize_for_forge(body)

    header = f"*CI analysis by {model_name}*\n\n"
    footer = "\n\n---\n*This analysis was generated by an AI and may contain errors.*"
    return header + body + footer


def _post_ci_feedback(failure_data: dict, report_content: str) -> None:
    """Post the CI analysis summary as a comment on the forge change.

    Errors are logged but never re-raised.
    """
    if not CONFIG.get("feedback_enabled"):
        return

    try:
        forge = create_forge_client(CONFIG)
        change_number = str(failure_data["change_number"])
        project = failure_data["project"]
        model_name = CONFIG.get("model", "claude-sonnet-4-6")

        change_info = forge.get_change(change_number, project)
        comment = _build_forge_comment(report_content, model_name)

        print(f"\n📤 Posting CI analysis feedback to {change_info.forge_type}...")
        ok = forge.post_feedback(change_info, comment, vote=None, line_comments=[])
        if ok:
            print("   ✅ Feedback posted successfully")
        else:
            print("   ⚠️  Feedback post returned failure (see warnings above)")
    except Exception as exc:
        print(f"   ⚠️  Could not post forge feedback: {exc}")


def create_report_filename(output_dir, project, change_number, patchset, sequence):
    """Generate a timestamped report filename."""
    project_slug = slugify(project.split("/")[-1])
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return Path(output_dir) / f"ci_failure_{project_slug}_{change_number}_ps{patchset}_{timestamp}_{sequence}.md"


async def analyze_failure(failure_data, output_dir=None, print_prompt=False):
    """
    Analyze CI failures for a single change using an AI agent.

    Args:
        failure_data: Dict containing change info and list of failing jobs
        output_dir: Override output directory (defaults to config value)
        print_prompt: If True, print the formatted prompt and exit without calling AI.
                      Use this with other AI tools (Cursor, Claude.ai, etc.)

    Returns:
        Path to the generated report file, or None on failure
    """
    from agents_lib import create_model_client as _create_model_client

    change_number = str(failure_data["change_number"])
    patchset = str(failure_data["patchset"])
    project = failure_data["project"]
    pipeline = failure_data["pipeline"]
    gerrit_url = failure_data.get(
        "gerrit_url",
        f"{CONFIG['gerrit_base_url']}/c/{project}/+/{change_number}",
    )
    jobs = failure_data["jobs"]
    sequence = failure_data.get("sequence", 1)

    if output_dir is None:
        output_dir = CONFIG["reports_output_dir"]
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    report_file = create_report_filename(output_dir, project, change_number, patchset, sequence)

    print(f"\n{'='*80}")
    print("  CI Failure Analysis")
    print(f"{'='*80}")
    print(f"  Project:      {project}")
    print(f"  Change:       #{change_number}")
    print(f"  Patchset:     PS{patchset}")
    print(f"  Pipeline:     {pipeline}")
    print(f"  Failing jobs: {len(jobs)}")
    print(f"  Gerrit:       {gerrit_url}")
    print(f"  Report:       {report_file.name}")
    print(f"{'='*80}\n")

    _provider = CONFIG.get("model_provider", "anthropic")
    prompt = get_ci_failure_prompt(
        project=project,
        change_number=change_number,
        patchset=patchset,
        pipeline=pipeline,
        gerrit_base_url=CONFIG["gerrit_base_url"],
        zuul_base_url=CONFIG["zuul_base_url"],
        zuul_tenant=CONFIG["zuul_tenant"],
        failing_jobs=jobs,
        output_file=str(report_file),
        provider=_provider,
        save_path=str(report_file),
    )

    from agents_lib import load_context_section as _lcs  # pylint: disable=import-outside-toplevel
    _ctx = _lcs(CONFIG, "ci_failure")
    if _ctx:
        prompt = _ctx + "\n\n---\n\n" + prompt

    if print_prompt:
        print("=" * 80)
        print("FORMATTED PROMPT (--print-prompt mode)")
        print("Copy the text below and paste into your AI tool of choice.")
        print("=" * 80)
        print(prompt)
        print("=" * 80)
        print(f"\nReport would be saved to: {report_file}")
        print("\nTo use with an AI tool other than Claude Code:")
        print("  1. Copy the prompt above")
        print("  2. Paste into your preferred AI assistant")
        print("  3. Instruct it to write the report to the path shown above")
        return None

    print("Starting AI-powered CI failure analysis...\n")
    print("  (The AI agent will fetch logs from Zuul and analyze each failing job)\n")

    result = None
    usage_info = None

    try:
        _client = _create_model_client(CONFIG)
        _res = await _client.query(
            prompt=prompt,
            tools=["Bash", "WebFetch", "Write"],
            on_progress=lambda text: print(f"  {text}"),
        )
        result = _res.text
        usage_info = format_usage_info(
            usage_data=_res.usage,
            cost_usd=_res.cost_usd,
            model=_res.model,
            duration_ms=_res.duration_ms,
        )

        print(f"\n{'='*80}")
        print("  Analysis Complete!")
        print(f"{'='*80}")
        if result:
            preview = result[:400].replace("\n", " ")
            print(f"\n  Summary: {preview}...")

        # Append token usage to the report
        if report_file.exists():
            if usage_info:
                existing = report_file.read_text()
                if "## Token Usage & Cost" not in existing:
                    report_file.write_text(existing + "\n\n---\n\n" + usage_info)
            print(f"\n  Report saved: {report_file}")
            _post_ci_feedback(failure_data, report_file.read_text())
            return report_file
        if result:  # file not found — save result text directly
            print("\n  Warning: Report file not found — saving AI result directly...")
            content = result
            if usage_info:
                content += "\n\n---\n\n" + usage_info
            report_file.write_text(content)
            print(f"  Saved to: {report_file}")
            _post_ci_feedback(failure_data, content)
            return report_file
        print(f"\n  Warning: No report was generated for change #{change_number}")
        return None

    except Exception as e:
        print(f"\n  Error during analysis: {e}")
        import traceback
        traceback.print_exc()
        return None


def main():
    parser = argparse.ArgumentParser(
        description="Analyze CI failures for an OpenStack Gerrit change",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Analyze using failure data JSON (standard usage)
  %(prog)s --failure-data /tmp/failure_data.json

  # Print prompt only — paste into any AI tool (Cursor, Claude.ai, etc.)
  %(prog)s --failure-data /tmp/failure_data.json --print-prompt

  # Save report to a custom directory
  %(prog)s --failure-data /tmp/failure_data.json --output-dir ~/my_ci_reports

Failure data JSON format:
  {
    "change_number": "982567",
    "patchset": "3",
    "project": "openstack/octavia",
    "pipeline": "check",
    "gerrit_url": "https://review.opendev.org/c/openstack/octavia/+/982567",
    "jobs": [
      {
        "job_name": "octavia-v2-dsvm-scenario-centos-9-stream-ovn",
        "uuid": "abc123...",
        "log_url": "https://storage.bhs.logs.ovh.net/v1/.../",
        "duration": 2843.0,
        "voting": true,
        "end_time": "2026-04-30T10:47:23",
        "nodeset": "centos-9-stream"
      }
    ]
  }
        """,
    )

    parser.add_argument(
        "--failure-data",
        required=True,
        metavar="FILE",
        help="JSON file containing failure information (jobs, log URLs, change details)",
    )
    parser.add_argument(
        "--print-prompt",
        action="store_true",
        help=(
            "Print the formatted analysis prompt and exit without invoking AI. "
            "Useful for using with other AI tools (Cursor, Claude.ai, Copilot, etc.)"
        ),
    )
    parser.add_argument(
        "--output-dir",
        metavar="DIR",
        help="Directory to save the report (overrides config)",
    )

    args = parser.parse_args()

    failure_data_file = Path(args.failure_data)
    if not failure_data_file.exists():
        print(f"Error: failure data file not found: {failure_data_file}", file=sys.stderr)
        sys.exit(1)

    with open(failure_data_file, encoding='utf-8') as f:
        failure_data = json.load(f)

    asyncio.run(analyze_failure(
        failure_data=failure_data,
        output_dir=args.output_dir,
        print_prompt=args.print_prompt,
    ))


def cli_main():
    """Entry point for console_scripts."""
    main()


if __name__ == "__main__":
    cli_main()
