"""
Parse generated review markdown to extract structured data for posting back to
the source forge (Gerrit, GitHub, GitLab).

The review prompt template specifies a particular output structure, but the AI
may vary it. All functions here are defensive and return sensible defaults
when expected sections are absent.
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "agents_lib"))
from agents_lib import LineComment, sanitize_for_forge


# ── helpers ──────────────────────────────────────────────────────────────────

def _section(content: str, *headers: str) -> str:
    """Extract the text of the first matching section (up to the next same-level header)."""
    for header in headers:
        # Match the header line and capture everything until the next heading at same or higher level
        level = len(re.match(r'^(#+)', header).group(1)) if re.match(r'^(#+)', header) else 2
        pattern = re.escape(header) + r'(.*?)(?=\n#{1,' + str(level) + r'} |\Z)'
        m = re.search(pattern, content, re.DOTALL | re.IGNORECASE)
        if m:
            return m.group(1).strip()
    return ""


def _first_n_chars(text: str, n: int) -> str:
    """Return at most n chars, cutting at a paragraph boundary if possible."""
    if len(text) <= n:
        return text
    cut = text.rfind("\n\n", 0, n)
    return text[:cut] if cut > n // 2 else text[:n]


# ── public API ────────────────────────────────────────────────────────────────

def extract_forge_comment(review_content: str, model_name: str) -> str:
    """Build the forge comment from the review markdown.

    Extracts: review summary section (top of file), test results table, key
    findings, and verdict — capped at 8000 chars (safe limit for all forges).

    Args:
        review_content: Full text of the generated review markdown.
        model_name:     Model identifier for the attribution line.

    Returns:
        Formatted comment string, including AI attribution header/footer.
    """
    MAX_CHARS = 7500

    # Strip token-usage section (appended by the agent runner, not part of review)
    clean = re.split(r'\n---\n\n## Token Usage', review_content, maxsplit=1)[0].strip()
    # Also strip the DevStack integration test section which can be very long
    clean = re.split(r'\n## DevStack Integration Testing\b', clean, maxsplit=1)[0].strip()
    clean = re.split(r'\n## Test Environment\b', clean, maxsplit=1)[0].strip()
    clean = re.split(r'\n## Tests Executed\b', clean, maxsplit=1)[0].strip()

    # The clean portion is typically the Review Summary section — use it as-is
    body = _first_n_chars(clean, MAX_CHARS)
    body = sanitize_for_forge(body)

    attribution_header = f"*Reviewed by {model_name}*\n\n"
    attribution_footer = "\n\n---\n*This review was generated by an AI and may contain errors.*"

    return attribution_header + body + attribution_footer


def extract_line_comments(review_content: str) -> list:
    """Parse inline line comments from the review markdown.

    Looks for the structured format produced by the code review prompt:

        ### File: `octavia/path/to/file.py`

        **Line 45-52**:
        - **Comment**: explanation

    Returns a list of LineComment objects. Returns an empty list if the
    section is absent or no line references can be parsed.
    """
    comments: list[LineComment] = []

    # Find the Detailed Review Comments section
    section_m = re.search(
        r'## Detailed Review Comments\s*(.*?)(?=\n## |\Z)',
        review_content,
        re.DOTALL | re.IGNORECASE,
    )
    if not section_m:
        return comments

    section = section_m.group(1)

    # Split into per-file blocks: ### File: `path/to/file.py`
    # Prepend a newline so the first file header is also caught by \n### pattern
    file_blocks = re.split(r'\n### File:\s*`?([^`\n]+)`?\s*\n', "\n" + section)
    # file_blocks is: [preamble, file1, content1, file2, content2, ...]

    i = 1  # skip preamble
    while i + 1 < len(file_blocks):
        file_path = file_blocks[i].strip()
        block_content = file_blocks[i + 1]
        i += 2

        # Match **Line N**: or **Lines N-M**: patterns.
        # The dash between line numbers may be a hyphen (-) or an en-dash (–).
        line_refs = re.split(r'\*\*Lines?\s+(\d+)(?:[-–](\d+))?\*\*\s*', block_content)
        # line_refs: [pre, line_start1, line_end1_or_None, body1, ...]

        j = 1
        while j + 2 < len(line_refs):
            line_start = int(line_refs[j])
            line_end_raw = line_refs[j + 1]
            line_end = int(line_end_raw) if line_end_raw else None
            body = line_refs[j + 2]

            # Extract just the comment text (up to next line-ref pattern)
            comment_text = _extract_comment_text(body)
            if comment_text:
                comments.append(LineComment(
                    file_path=file_path,
                    line=line_start,
                    message=comment_text,
                    line_end=line_end,
                ))
            j += 3

    return comments


def _extract_comment_text(raw: str) -> str:
    """Pull the human-readable comment from a line-reference body block."""
    # Look for "- **Comment**: ..." pattern
    m = re.search(r'\*\*Comment\*\*:\s*(.+?)(?=\n-\s+\*\*|\Z)', raw, re.DOTALL)
    if m:
        return sanitize_for_forge(m.group(1).strip())
    # Fall back: first non-empty line that isn't a severity/suggestion marker
    for line in raw.splitlines():
        line = line.strip().lstrip('- ')
        if line and not line.startswith('**Severity') and not line.startswith('**Suggestion'):
            return sanitize_for_forge(line)
    return ""


def determine_vote(review_content: str, config: dict) -> int | None:
    """Determine the forge vote score from the review verdict.

    Checks for recommendation/verdict patterns and maps to:
        +1  → approval_score  (default 1)
         0  → minor_score     (default 0)
        -1  → major_score     (default -1)
        None → voting disabled

    Args:
        review_content: Full text of the generated review markdown.
        config:         Flat config dict with feedback_* keys.

    Returns:
        Integer vote or None if voting is disabled.
    """
    if not config.get("feedback_voting", True):
        return None

    approval_score = config.get("feedback_approval_score", 1)
    major_score = config.get("feedback_major_score", -1)
    minor_score = config.get("feedback_minor_score", 0)

    # Normalise for pattern matching
    text = review_content.lower()

    # Strong approval signals
    approve_patterns = [
        r'\brecommendation[:\s*]*.*\bapprove\b',
        r'\bverdict[:\s*]*.*\bapprove\b',
        r'✅.*\bapprove\b',
        r'\bapprove\b.*(?:ready|merge|lgtm)',
        r'✅\s*approve',
    ]
    for pat in approve_patterns:
        if re.search(pat, text):
            # Double-check there are no critical/major blockers mentioned
            if not _has_blocking_issues(review_content):
                return approval_score

    # Request-changes signals — check for critical / major issues
    request_change_patterns = [
        r'\brequest\s+changes?\b',
        r'🔄.*request',
        r'\bverdict[:\s*]*.*\bchanges?\b',
    ]
    for pat in request_change_patterns:
        if re.search(pat, text):
            if _has_blocking_issues(review_content):
                return major_score
            return minor_score

    # Required-change markers without explicit verdict
    if _has_blocking_issues(review_content):
        return major_score

    # Minor suggestions only
    if re.search(r'🟡|minor|suggestion|nit\b', text):
        return minor_score

    return None


def _has_blocking_issues(review_content: str) -> bool:
    """Return True if the review contains critical or major issues."""
    blocking_patterns = [
        r'🔴',           # red circle = critical
        r'\bmust\s+fix\b',
        r'\bcritical\b(?!\s+path)',  # "critical path" is not a blocking issue
        r'\bsecurity\s+(?:issue|vulnerability|bug|risk)\b',
        r'\bbreaking\s+change\b',
    ]
    for pat in blocking_patterns:
        if re.search(pat, review_content, re.IGNORECASE):
            return True
    return False


def extract_ci_forge_comment(report_content: str, model_name: str) -> str:
    """Build a forge comment from a CI failure analysis report.

    Extracts the overall recommendation and per-job summary table.
    Always informational (no vote).

    Args:
        report_content: Full text of the CI failure analysis markdown.
        model_name:     Model identifier for the attribution line.

    Returns:
        Formatted comment string, including AI attribution.
    """
    MAX_CHARS = 6000

    # Strip token usage section
    clean = re.split(r'\n---\n\n## Token Usage', report_content, maxsplit=1)[0].strip()

    # Try to extract the Overall Recommendation section
    rec_section = _section(clean, "## Overall Recommendation", "## Recommendation")

    # Try to extract the failing jobs table (first markdown table in the file)
    table_m = re.search(r'(\|[^\n]+\|\n\|[-:| ]+\|\n(?:\|[^\n]+\|\n)+)', clean)
    table = table_m.group(1).strip() if table_m else ""

    parts = []
    if rec_section:
        parts.append("## Overall Recommendation\n\n" + _first_n_chars(rec_section, 2000))
    if table:
        parts.append("## Failing Jobs\n\n" + table)
    if not parts:
        # Fallback: first N chars of the report
        parts.append(_first_n_chars(clean, MAX_CHARS))

    body = "\n\n".join(parts)
    body = _first_n_chars(body, MAX_CHARS)
    body = sanitize_for_forge(body)

    attribution_header = f"*CI analysis by {model_name}*\n\n"
    attribution_footer = "\n\n---\n*This analysis was generated by an AI and may contain errors.*"

    return attribution_header + body + attribution_footer
