"""Unit tests for agents_lib.forge_feedback (shared forge feedback utilities)."""
from agents_lib.forge_feedback import (
    extract_forge_comment,
    extract_line_comments,
    extract_ci_forge_comment,
    extract_devstack_forge_comment,
    determine_vote,
    _has_blocking_issues,
)


# ── Fixtures ──────────────────────────────────────────────────────────────────

_APPROVE_REVIEW = """\
## Review Summary

### Test Results
| Suite | Status |
|-------|--------|
| Unit  | ✅ PASS |

### Verdict: ✅ APPROVE

No issues found. The change is clean and well-tested.
"""

_REQUEST_CHANGES_CRITICAL = """\
## Review Summary

### Verdict: 🔄 Request Changes

#### Critical 🔴
1. **Missing input validation** — values are not sanitised before use.

#### Major 🟡
2. **Race condition** in the health-manager path.
"""

_REQUEST_CHANGES_MINOR = """\
## Review Summary

### Verdict: 🔄 Request Changes

Only minor nit-picks; no blocking issues.

#### Minor 🔵
1. Typo: "immuatable" → "immutable"
"""

_REVIEW_WITH_LINE_COMMENTS = """\
## Code Analysis

Overall the change looks good.

## Detailed Review Comments

### File: `octavia/api/v2/controllers/listener.py`

**Lines 107–126**:
- **Severity**: Major
- **Comment**: The error path silently swallows exceptions when force_update is True.
- **Suggestion**: Always raise ImmutableObject when repo returns False.

**Line 248**:
- **Severity**: Minor
- **Comment**: Typo in constant name.

### File: `octavia/db/repositories.py`

**Lines 355-402**:
- **Comment**: Docstring does not document the force_update parameter.

## Final Verdict

**Recommendation**: 🔄 Request Changes
"""

_REVIEW_WITH_TOKEN_USAGE = """\
## Summary

Short summary here.

---

## Token Usage & Cost

- Input tokens: 1234
- Output tokens: 456
"""

_REVIEW_WITH_DEVSTACK_SECTION = """\
## Summary

Short summary here.

## Tests Executed

This section is very long and should be stripped.
Lots of test output...
"""

_DEFAULT_CONFIG = {
    "feedback_voting": True,
    "feedback_approval_score": 1,
    "feedback_major_score": -1,
    "feedback_minor_score": 0,
}


# ── extract_forge_comment ─────────────────────────────────────────────────────

class TestExtractForgeComment:
    def test_includes_attribution_header(self):
        result = extract_forge_comment(_APPROVE_REVIEW, "claude-sonnet-4-6")
        assert "*Reviewed by claude-sonnet-4-6*" in result

    def test_includes_attribution_footer(self):
        result = extract_forge_comment(_APPROVE_REVIEW, "claude-sonnet-4-6")
        assert "generated by an AI" in result

    def test_includes_review_body(self):
        result = extract_forge_comment(_APPROVE_REVIEW, "claude-sonnet-4-6")
        assert "APPROVE" in result

    def test_strips_token_usage_section(self):
        result = extract_forge_comment(_REVIEW_WITH_TOKEN_USAGE, "claude-sonnet-4-6")
        assert "Token Usage" not in result
        assert "1234" not in result

    def test_strips_tests_executed_section(self):
        result = extract_forge_comment(_REVIEW_WITH_DEVSTACK_SECTION, "claude-sonnet-4-6")
        assert "Tests Executed" not in result
        assert "lots of test output" not in result.lower()

    def test_sanitizes_credentials(self):
        review = "## Summary\n\nexport OS_PASSWORD=supersecret\n\nGood change overall.\n"
        result = extract_forge_comment(review, "model")
        assert "supersecret" not in result
        assert "[REDACTED]" in result

    def test_caps_at_max_chars(self):
        long_review = "x" * 10_000
        result = extract_forge_comment(long_review, "model")
        assert len(result) < 10_000

    def test_empty_input_returns_attribution_only(self):
        result = extract_forge_comment("", "model")
        assert "*Reviewed by model*" in result


# ── extract_line_comments ─────────────────────────────────────────────────────

class TestExtractLineComments:
    def test_returns_empty_list_when_no_section(self):
        assert extract_line_comments("No Detailed Review Comments here.") == []

    def test_parses_file_and_line(self):
        comments = extract_line_comments(_REVIEW_WITH_LINE_COMMENTS)
        assert len(comments) >= 1
        paths = {c.file_path for c in comments}
        assert "octavia/api/v2/controllers/listener.py" in paths

    def test_en_dash_range_parsed(self):
        comments = extract_line_comments(_REVIEW_WITH_LINE_COMMENTS)
        lc = next(c for c in comments if c.file_path == "octavia/api/v2/controllers/listener.py"
                  and c.line == 107)
        assert lc.line_end == 126

    def test_hyphen_range_parsed(self):
        comments = extract_line_comments(_REVIEW_WITH_LINE_COMMENTS)
        lc = next(c for c in comments if c.file_path == "octavia/db/repositories.py")
        assert lc.line == 355
        assert lc.line_end == 402

    def test_single_line_no_end(self):
        comments = extract_line_comments(_REVIEW_WITH_LINE_COMMENTS)
        lc = next(c for c in comments if c.line == 248)
        assert lc.line_end is None

    def test_comment_text_extracted(self):
        comments = extract_line_comments(_REVIEW_WITH_LINE_COMMENTS)
        lc = next(c for c in comments if c.line == 107)
        assert "silently swallows" in lc.message

    def test_comment_text_sanitized(self):
        review = """\
## Detailed Review Comments

### File: `foo/bar.py`

**Line 10**:
- **Comment**: Set PASSWORD=hunter2 directly, which is insecure.
"""
        comments = extract_line_comments(review)
        assert len(comments) == 1
        assert "hunter2" not in comments[0].message
        assert "[REDACTED]" in comments[0].message

    def test_multiple_files(self):
        comments = extract_line_comments(_REVIEW_WITH_LINE_COMMENTS)
        paths = {c.file_path for c in comments}
        assert len(paths) >= 2


# ── determine_vote ────────────────────────────────────────────────────────────

class TestDetermineVote:
    def test_approve_returns_positive_score(self):
        assert determine_vote(_APPROVE_REVIEW, _DEFAULT_CONFIG) == 1

    def test_critical_issues_returns_negative_score(self):
        assert determine_vote(_REQUEST_CHANGES_CRITICAL, _DEFAULT_CONFIG) == -1

    def test_minor_only_returns_zero(self):
        assert determine_vote(_REQUEST_CHANGES_MINOR, _DEFAULT_CONFIG) == 0

    def test_voting_disabled_returns_none(self):
        config = {**_DEFAULT_CONFIG, "feedback_voting": False}
        assert determine_vote(_APPROVE_REVIEW, config) is None

    def test_approve_with_blocker_returns_negative(self):
        # If the review says Approve but also has 🔴, be conservative
        mixed = _APPROVE_REVIEW + "\n\n#### Critical Issues 🔴\n1. Something bad.\n"
        assert determine_vote(mixed, _DEFAULT_CONFIG) == -1

    def test_custom_scores_respected(self):
        config = {
            "feedback_voting": True,
            "feedback_approval_score": 2,
            "feedback_major_score": -2,
            "feedback_minor_score": 1,
        }
        assert determine_vote(_APPROVE_REVIEW, config) == 2
        assert determine_vote(_REQUEST_CHANGES_CRITICAL, config) == -2
        assert determine_vote(_REQUEST_CHANGES_MINOR, config) == 1

    def test_no_verdict_with_blockers_returns_negative(self):
        review = "This patch has a security vulnerability that must fix immediately."
        assert determine_vote(review, _DEFAULT_CONFIG) == -1

    def test_no_verdict_no_signals_returns_none(self):
        review = "The change looks okay. No issues noted."
        assert determine_vote(review, _DEFAULT_CONFIG) is None


# ── _has_blocking_issues ──────────────────────────────────────────────────────

class TestHasBlockingIssues:
    def test_red_circle_is_blocking(self):
        assert _has_blocking_issues("Found critical problem 🔴") is True

    def test_must_fix_is_blocking(self):
        assert _has_blocking_issues("This must fix before merge.") is True

    def test_critical_path_is_not_blocking(self):
        assert _has_blocking_issues("This is in the critical path.") is False

    def test_security_vulnerability_is_blocking(self):
        assert _has_blocking_issues("There is a security vulnerability here.") is True

    def test_breaking_change_is_blocking(self):
        assert _has_blocking_issues("This is a breaking change.") is True

    def test_clean_review_is_not_blocking(self):
        assert _has_blocking_issues("Looks good, no issues.") is False


# ── extract_ci_forge_comment ──────────────────────────────────────────────────

class TestExtractCIForgeComment:
    _CI_REPORT = """\
## Overall Recommendation

RE-RUN ONLY — all failures are infrastructure issues.

## Failing Jobs

| Job | Category | Voting |
|-----|----------|--------|
| octavia-dsvm-scenario | ENVIRONMENTAL | yes |

## Detailed Analysis

...lots of log analysis here...

---

## Token Usage & Cost

- Input tokens: 500
"""

    def test_includes_attribution_header(self):
        result = extract_ci_forge_comment(self._CI_REPORT, "claude-sonnet-4-6")
        assert "*CI analysis by claude-sonnet-4-6*" in result

    def test_includes_recommendation(self):
        result = extract_ci_forge_comment(self._CI_REPORT, "claude-sonnet-4-6")
        assert "RE-RUN ONLY" in result

    def test_includes_jobs_table(self):
        result = extract_ci_forge_comment(self._CI_REPORT, "claude-sonnet-4-6")
        assert "ENVIRONMENTAL" in result

    def test_strips_token_usage(self):
        result = extract_ci_forge_comment(self._CI_REPORT, "claude-sonnet-4-6")
        assert "Input tokens" not in result

    def test_sanitizes_credentials(self):
        report = "## Overall Recommendation\n\nRE-RUN. Auth token: abc123abc123abc123abc123\n"
        result = extract_ci_forge_comment(report, "model")
        assert "abc123abc123abc123abc123" not in result


# ── extract_devstack_forge_comment ────────────────────────────────────────────

class TestExtractDevstackForgeComment:
    _DEVSTACK_REPORT = """\
# Code Review: openstack/octavia

Original review content — should be excluded.

---

# DevStack Integration Testing

## Test Environment
- DevStack path: /opt/stack

## Tests Executed

### Test 1: Load Balancer Creation
**Result:** ✅ PASS

## Test Results Summary

**Overall Status**: ✅ PASS

**Tests Passed:** 2/2
**Tests Failed:** 0

**Key Findings:**
- Load balancer created successfully

---

## Token Usage & Cost

- Input tokens: 800
"""

    def test_includes_attribution_header(self):
        result = extract_devstack_forge_comment(self._DEVSTACK_REPORT, "claude-sonnet-4-6")
        assert "claude-sonnet-4-6" in result

    def test_includes_attribution_footer(self):
        result = extract_devstack_forge_comment(self._DEVSTACK_REPORT, "claude-sonnet-4-6")
        assert "generated by an AI" in result

    def test_includes_overall_status(self):
        result = extract_devstack_forge_comment(self._DEVSTACK_REPORT, "claude-sonnet-4-6")
        assert "PASS" in result

    def test_excludes_original_review_content(self):
        result = extract_devstack_forge_comment(self._DEVSTACK_REPORT, "claude-sonnet-4-6")
        assert "Original review content" not in result

    def test_strips_token_usage(self):
        result = extract_devstack_forge_comment(self._DEVSTACK_REPORT, "claude-sonnet-4-6")
        assert "Input tokens" not in result

    def test_handles_missing_devstack_section(self):
        result = extract_devstack_forge_comment("# Some report\n\nContent here.", "model")
        assert len(result) > 0   # should not crash

    def test_caps_at_max_chars(self):
        long_report = "x" * 10_000
        result = extract_devstack_forge_comment(long_report, "model")
        assert len(result) < 6_500
